### ISSUE TITLE
Explain basic chef encrypted data bag scenario in readme

### ISSUE THREAD

**Issue by oponder** [jssjr/chef-tarsnap#13]
Hi,

Whats the right workflow for using this cookbook? I've been looking around and there is quite some documentation on encrypted data bags and such, but can't really find the 'right way' of setting this up so that my nodes can get access to the encrypted tarsnap_keys data bag.

How have you gone about setting this up for your own installations? 

I appreciate any response! 

Thanks, happy new year,
Oliver Ponder

**Comment by malbin** [comment]
hey @oponder,
I probably have a little bit of a hacky setup but I'll share it with you in the hopes that someone more knowledgeable comes around and points out a better way to do what I'm doing :)

First, I'd advise you to take a look over at https://github.com/Nordstrom/chef-vault -- I use this gem to manage my encrypted data bags and it works very well. I won't go into detail about how this gem works here (the documentation is excellent), but if you have more questions about it I'd be happy to answer them.

Also, my machines exist entirely within AWS:EC2. This means I have sort of a chicken-egg problem with new nodes. In order to add a new nodes pubkey to chef-vault, it has to already exist within my Chef infrastructure. I solve this in the following way.

I have a perl script that I use to create a node on EC2. I pass all of the machine information (name, region, EIP, role, etc) on the command line for use within the script. Once the machine is up I then bootstrap it with my "base" role (installs universal stuff that all of my machines need). At that point, I can add this new machine to my encrypted data bag's keys object (special object created by chef-vault that stores pubkeys of nodes that can decrypt the content of the associated object). In the perl script I have a hash of encrypted data bags, and so I literally just run through them and add the new node to each in a loop.

``` perl
foreach my $key (keys %enc_databags) {
    # pull out the array obj for each data bag
    foreach (@{$enc_databags{$key}}) {
        my $cmd = "knife encrypt update $key $_ -S \"name:$hostname\" --mode client";
        print $cmd,"\n";
        system($cmd);
    }
}
```

In this example, the `$hostname` is the name of the node that has been newly registered with my chef server. Once the node's pubkey has been added to my encrypted data bags I then add the remaining roles to its' run list and re-run `chef-client`. This goes through the rest of my recipes... One of which is for "tarsnap".

Since the new node has access to the encrypted data bag, I install my private key with the following (pared down) recipe:

``` ruby
chef_gem "chef-vault"
require 'chef-vault'

# using a placeholder data bag name here but you get the idea...
item = ChefVault::Item.load("data_bag_name", "tarsnap_key")
# store the actual contents of the "tarsnap_key" object in "key"
key = item["key"]

file "#{node['tarnsap']['key_path']}/#{node['tarsnap']['key_file']}" do
    owner user
    group user
    mode 0600
    # magic
    content key
    action :create
end
```

I hope that this is helpful for you... Let me know if you have any questions, and good luck!

**Comment by oponder** [comment]
@malbin 
Thanks for the quick reply and examples! I think I got the big picture. Going to give it a try!

**Comment by ghost** [comment]
I'm working on refactoring the cookbook now and I'll make some notes in the readme about this for the release.

**Comment by ghost** [comment]
@oponder @malbin 

Hi,

 Life knocked me back down, and I got to busy to take care of this. This cookbook is setup by default to use a encrypted databag. I know @malbin suggested chef-vault. I use chef-vault myself and I'm wondering if this is something you guys would prefer to be included as a option, while I'm working on the new version.

**Comment by oponder** [comment]
No worries gregf! 

Yeah! That would be awesome! I was looking for any strong opinion / best practice, as I don't have a good one myself yet.

**Comment by oponder** [comment]
Gonna go ahead and close this old issue :)
